### ISSUE TITLE
"container probing failed" error with simple nginx example

### ISSUE THREAD

**Issue by ryboe** [mutagen-io/mutagen-compose#1]
## The Error

I'm using mutagen 0.13.0-beta2 with Compose V2 and I'm unable to get this simple volume to sync.

```yaml
version: "3.9"

services:
  nginx:
    image: nginx:latest
    ports:
      - 8000:80
    volumes:
      - static:/usr/share/nginx/html

volumes:
  static:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true            # don't sync .git/ dirs
      mode: two-way-resolved # two way sync, but alpha wins all conflicts
    static:
      alpha: ./html
      beta: volume://static
```

```sh
$ mutagen compose up
[+] Running 3/3
 ⠿ Network foo_default      Created                                                                                                                                                             0.3s
 ⠿ Volume "foo_static"      Created                                                                                                                                                         
 ⠿ Container foo-mutagen-1  Started                                                                                                                                                             2.4s
Resuming existing forwarding sessions
Resuming existing synchronization sessions                                      
Creating synchronization session "static"                                       
Connecting to agent (POSIX)...                                                  
Error: unable to reconcile Mutagen sessions: unable to create synchronization session (static): unable to connect to beta: unable to connect to endpoint: unable to dial agent endpoint: unable to create agent command: unable to probe container: container probing failed under POSIX hypothesis (exit status 1) and Windows hypothesis (exit status 1)
```

I have a tiny HTML file at `./html/index.html`. I'm trying to mount the local `./html` directory into the `nginx` container at `/usr/share/nginx/html`.

## Versions

mutagen 0.13.0-beta2
docker compose 2.1.1
Docker Desktop 4.2.0
macOS 12.0.1
