### ISSUE TITLE
"Additional property sync is not allowed" on up command

### ISSUE THREAD

**Issue by WillyReyno** [mutagen-io/mutagen-compose#10]
Hello, I'm getting the following error when I run `mutagen-compose up`.

```
volumes.x-mutagen Additional property sync is not allowed
```

- Macbook Pro 14" (2021, M1 Pro chip)
- MacOS Monterey 12.1 
- Mutagen version:  0.13.0
- Mutagen Compose version:  0.13.0
- Compose version:  v2.2.3
- Docker version:  v20.10.7

Here's my simplified `docker-compose.yml` file: 
```yaml 
version: "3.8"

services:
  web:
    volumes:
      - code:/var/www/html
      
  x-mutagen:
    sync:
      defaults:
        ignore:
          vcs: true
      code:
        alpha: "."
        beta: "volume://code"
        mode: "two-way-resolved"

volumes:
  code:  
```

It's my very first time trying mutagen / mutagen-compose, hope you can help me with this!
