### ISSUE TITLE
Beta defaultOwner/defaultGroup can't find user available only in the container

### ISSUE THREAD

**Issue by vaughnkoch** [mutagen-io/mutagen-compose#12]
Using defaultOwner/defaultGroup with mutagen-compose, and a user that's only available in the container, produces this error when running `mutagen-compose up api`

`unable to lookup user by ID: user: unknown user foobar_user`

Here's how I add a user in the Dockerfile:

```
RUN addgroup --gid 1000 foobar_user && \
    adduser --uid 1000 --gid 1000 foobar_user
```

Here's the relevant part of my docker-compose:

```
x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
      mode: "two-way-resolved"

    mount-web-to-code:
      alpha: "./web"
      beta: "volume://mount-web-to-code"

    mount-api-to-code:
      alpha: "./api"
      beta: "volume://mount-api-to-code"

      configurationBeta:
        permissions:
            defaultOwner: "id:1000"
            defaultGroup: "id:1000"
```

This appears to work - first of all, mutagen-compose runs the container, and when I edit files on the host, the ownership is set to foobar_user.

However, using these permissions...

```
      configurationBeta:
        permissions:
            defaultOwner: "foobar_user"
            defaultGroup: "foobar_user"
```

...produces the following error:

```
 ⠿ Mutagen                       Error: unable to create synchronization session (mount-api-to-code):...           2.8s
unable to bring up Mutagen Compose sidecar service: unable to reconcile Mutagen sessions: unable to create synchronization session (mount-api-to-code): unable to connect to beta: unable to connect to endpoint: remote error: unable to create underlying endpoint: unable to create ownership specification: unable to lookup user by ID: user: unknown user foobar_user
```

Some thoughts:
- I'm able to go back and forth between working/not-working based on the defaultOwner and defaultGroup being set to ids vs named users.
- I don't know how to specify with docker-compose that the mutagen agent should be run as a user other than root, which may be relevant.
- foobar_user only exists in the container; maybe Mutagen is trying to look it up on the host, despite it only being listed in configurationBeta?
- If I don't set any defaultUser/defaultGroup, the file ownership is set to root, which doesn't work for my use case.
- The permissions only appear to be set for beta files that are updated in alpha, which makes sense.

Any thoughts? I looked all over the documentation and issues, but couldn't figure out how to address this.

```
$ mutagen-compose version
Mutagen version 0.13.0
Compose version v2.2.3
Docker version v20.10.7
```
