### ISSUE TITLE
conf(volume): unable to access files between containers

### ISSUE THREAD

**Issue by Guikingone** [mutagen-io/mutagen-compose#3]
Hi Mutagen team 👋🏻 

Sorry to create a new issue but I'm facing a very strange situation (I must admit that it's probably related to a configuration issue, I prefer to be honest 😄 ), I'm currently adding the mutagen sidecar service to a Symfony application (the demo one to be precise) and even if the PHP container works (I'm able to use it and see the Mutagen gains), the Nginx server seems to encounter some issues when accessing files and returning the front controller, here's the context: 

| Q                | A
| ---------------- | ---
macOS | **macOS Monterey (12.0.1) & M1 Pro ship**
| Docker version (Docker Desktop) | **4.2.0**
| Docker engine | **v20.10.10**
| Docker-Compose | **2.1.1**
| Mutagen version | **0.13.0-beta2**
| Mutagen-Compose version | **0.13.0-beta2**

The boot process seems to work when using `mutagen-compose up -d` but when I'm trying to access the application using `localhost:80`, I'm facing a `Files not found` error, after searching for more informations, it seems that the front controller (located in `public/index.php` isn't found by Nginx, problem is, the volume is "properly" shared and the configuration seems valid (I've compared it with the example provided in the official documentation of Mutagen and except the forward rules, nothing seems wrong 🤔 

If it can help, I've created a repository that contains the whole configuration: https://github.com/Guikingone/MutagenSf, here's the `docker-compose.override.yml` file: 

```yaml
version: '3'

services:
  php:
    volumes:
      - php:/srv/app

  nginx:
    volumes:
      - php:/srv/app

volumes:
  php:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    php:
      alpha: '.'
      beta: 'volume://php'
      mode: 'two-way-safe'
      ignore:
        paths:
          - '.idea'
          - '.git'
          - '.github'
          - '.gitignore'
          - 'README.md'
```

Again, it's probably a configuration issue but I don't find it and its annoying as the CLI seems to work 🙁 

Thanks again for the help and sorry for the issue 🙂

**Comment by xenoscopic** [comment]
The configuration here looks fine.  

If you drop into the `nginx` container (or other containers), are you able to see any files present in `/srv/app`?  E.g. via

```
mutagen-compose exec nginx /bin/sh
ls /srv/app
```

Maybe also check the `mutagen` container:

```
mutagen-compose exec mutagen /bin/sh
ls /volumes/php
```

Other things I can think of that might possibly be an issue:

- Perhaps Compose V2 merges volume listings differently (even though it shouldn't according to the Compose Spec, but bugs are always a possibility) and the other mounts (e.g. `nginx.conf`) aren't being handled properly
- Perhaps Compose is getting confused by having a volume and service with the same name (which it also shouldn't)

Can you share the exact commands that you're using to bring up the project?

**Comment by Guikingone** [comment]
Hi @xenoscopic 👋🏻 

Yes, for sure, when running the commands listed above, the files are present.

In order to boot the project, here's the commands that I use:

```bash
mutagen daemon start
mutagen-compose up -d
```

I don't know if it could be related but I cannot launch `mutagen-compose up -d` without starting the daemon manually, here's the error display if I try: 

```bash
[+] Running 0/2
[+] Running 0/2tagen-mutagen-1  Stopping                                                                                                                                                                   6.5s
 ⠿ Container mutagen-mutagen-1  Error while Stopping                                                                                                                                                       6.5s
 ⠿ Mutagen                      Error: unable to connect to Mutagen daemon: connection timed out (is the daemon running?)                                                                                  6.5s
unable to stop Mutagen Compose sidecar service: unable to pause Mutagen sessions: unable to connect to Mutagen daemon: connection timed out (is the daemon running?)
```

Thanks again for the support 🙂

**Comment by xenoscopic** [comment]
I'm not sure why you're seeing the daemon autostart issue - all Mutagen Compose operations should automatically start the Mutagen daemon.  Is there any chance you have `MUTAGEN_DISABLE_AUTOSTART=1` set in your environment?

Regarding the inaccessible PHP file, if the files are there, my guess is that it's a permissions issue being reported as a `Files not found` error.  Mutagen will synchronize files in as `root` with restrictive default permissions (`0700`/`0600` for directories/files, respectively), and the `nginx`/`php` containers are almost certainly not running as `root`.  I would try a configuration along the lines of:

```yaml
version: '3'

services:
  php:
    volumes:
      - php:/srv/app

  nginx:
    volumes:
      - php:/srv/app

volumes:
  php:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    php:
      alpha: '.'
      beta: 'volume://php'
      mode: 'two-way-safe'
      ignore:
        paths:
          - '.idea'
          - '.git'
          - '.github'
          - '.gitignore'
          - 'README.md'
      configurationBeta:
        permissions:
          defaultFileMode: 0o644
          defaultDirectoryMode: 0o755
```

That should at least tell you if it's a permissions issue or not.  Once that's understood, you can refine the permissions a bit, ideally running as whatever the default user for the container is, probably `www-data` or similar, but in either case probably something with a uid/gid of 1000.

**Comment by Guikingone** [comment]
Hi 👋🏻 

Regarding `MUTAGEN_DISABLE_AUTOSTART=1`, it's not set in my env. 

Regarding the configuration: 

```yaml
# ...
      configurationBeta:
        permissions:
          defaultFileMode: 0o644
          defaultDirectoryMode: 0o755
```

It doesn't solve the issue so I guess it's a permissions issues, by default, `Nginx` doesn't seems to define a user, except `nginx` (on group `nginx`) on `public` directory, on its side, `PHP` is running using `root`.

**Comment by xenoscopic** [comment]
I believe the problem persisted in your case after the permission change because the `php` volume wasn't removed between the changes, meaning that files with the old permissions were still there, which Mutagen won't touch (it won't change permissions for files it's not updating).

Fortunately, I was able to reproduce the `404` you saw.

Looking in `/var/log/nginx/project_error.log`, I see "FastCGI sent in stderr: "Primary script unknown" while reading response header from upstream", indicating that the `php` container (which seems to run as `www-data`) isn't able to access the PHP file.

When I added the `defaultFileMode`/`defaultDirectoryMode` configuration above and restarted synchronization from scratch by removing the volume (e.g. with `mutagen-compose down --volumes`/`mutagen-compose up`), I now receive the following error in my browser:

```
Warning: require_once(/srv/app/vendor/autoload_runtime.php): failed to open stream: No such file or directory in /srv/app/public/index.php on line 5

Fatal error: require_once(): Failed opening required '/srv/app/vendor/autoload_runtime.php' (include_path='.:/usr/local/lib/php') in /srv/app/public/index.php on line 5
```

I believe this is due to me not having the Composer packages installed, but I'm not really a PHP person so I'm not really sure how to do that in the context of this project.  But removing the volume after changing the permissions should solve the issue.  Do let me know if that's not the case.

The reason Mutagen doesn't edit the permissions of existing files is to allow for manual overrides of file permissions and to avoid excessive filesystem scanning and system call overhead.

---

Regarding the autostart issue - that's a problem with Mutagen Compose that I'll need to fix.  I've opened a separate issue (#5) to track that.  Sorry about that one.

**Comment by Guikingone** [comment]
Hi @xenoscopic 👋🏻 

Thanks a lot for the support, the `mutagen-compose down --volumes` command + the directory/file permissions changes fixed the issue, it seems related to permissions granted by Nginx (as PHP works perfectly), I'm gonna investigate more to improve the `docker-compose.override.yml` configuration and see if I can set the permissions using Mutagen, thanks a lot for your time and help. 

Regarding #5, no problem, I'll be waiting for the fix to update my installation 🙂

**Comment by kwolniak** [comment]
Hi, I have the same issue with "file not found", and when i set this file/directory permissions the app works, but php (my application) is not able to write to filesystem. I'm getting error from my app: "Unable to write in the "cache" directory".
So it solves one problem but creates another.

**Comment by xenoscopic** [comment]
@kwolniak You'll probably want to try broader permissions if you want the files and directories to be accessible by more than one UID/GID.  A setting of `0o777` may be more appropriate for directories, `0o666` for files.

You could also try a hub-and-spoke setup with multiple volumes and sync sessions (with different UIDs/GIDs), using your local system's copy of the files as the "hub" in a hub-and-spoke synchronization model.

If you do change the settings, then you'll want to remove any existing volumes (with `mutagen-compose down --volumes`) before bringing the project back up, because Mutagen will only apply these modes to newly sync'd or updated directories/files.

**Comment by kwolniak** [comment]
[xenoscopic](https://github.com/xenoscopic) It looks like

```
            configurationBeta:
                permissions:
                    defaultOwner: "id:33"
                    defaultGroup: "id:33"
                    defaultFileMode: 0o644
                    defaultDirectoryMode: 0o755
```

solves my problems. Thanks.
