### ISSUE TITLE
Permission denied opening files on the container

### ISSUE THREAD

**Issue by Lzok** [mutagen-io/mutagen-compose#6]
Hello, how are you?
I am having troubles with permissions on my container. It's a NextJS project that works fine with docker-compose on Mac but well, due to the poor performance of volumes on Mac, I'm trying Mutagen.

The command I am using is `mutagen-compose up`

#### Error
```bash
frontend        | npm ERR! code EACCES
frontend        | npm ERR! syscall open
frontend        | npm ERR! path /opt/app/package.json
frontend        | npm ERR! errno -13
frontend        | npm ERR! Error: EACCES: permission denied, open '/opt/app/package.json'
frontend        | npm ERR!  [Error: EACCES: permission denied, open '/opt/app/package.json'] {
frontend        | npm ERR!   errno: -13,
frontend        | npm ERR!   code: 'EACCES',
frontend        | npm ERR!   syscall: 'open',
frontend        | npm ERR!   path: '/opt/app/package.json'
frontend        | npm ERR! }
```

#### Versions
```bash
> mutagen-compose version
Mutagen version 0.13.0-beta3
Compose version v2.1.1
Docker version v20.10.7
```

#### Dockerfile
```bash
FROM node:16.1.0-alpine3.11 as dev
ENV PATH /opt/app/node_modules/.bin:$PATH
EXPOSE 3000

WORKDIR /opt/app
RUN chown node:node .

USER node

COPY --chown=node:node package.json package-lock.json /opt/app/
RUN npm ci && npm cache clean --force

COPY --chown=node:node . /opt/app
CMD ["npm", "start"]
```

#### Docker-compose (part of it)
```yml
version: '3.8'

services:
  frontend:
    build:
      context: ../client
      dockerfile: Dockerfile
      target: dev
    container_name: container-frontend
    command: npm run dev
    env_file:
      - ../client/.env.local
    ports:
      - '3000:3000'
    volumes:
      - code-front:/opt/app
      - node-modules-front:/opt/app/node_modules
    depends_on:
      - backend
    restart: always

volumes:
  node-modules-front:
  code-front:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code-front:
      ignore:
        paths:
          - '../client/node_modules'
      alpha: "../client"
      beta: "volume://code-front"
      mode: "two-way-resolved"
```

Do you have any clue on what am I missing?

Thanks!

Edit: In the same docker-compose file I have the backend service, using other mutagen volume and it works ok.

**Comment by xenoscopic** [comment]
Mutagen will operate as `root` inside the Mutagen sidecar service, so any files it creates will default to `root` ownership and access.  Your `frontend` service is running as the `node` user, with UID (and corresponding GID) `1000`, so it's not able to access the files in the volume.  There are two options:

1. Set the permissions to keep `root` ownership but allow broader access, or
2. Set the ownership to `node` (which is what I'd recommend if this code is only needed by the `frontend` service)

Now since the `node` user/group are specific to the `node` image and `frontend` container, you'll have to set the permissions by UID/GID (`1000` in this case), so you could use a configuration that looks something like:

 ```
x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code-front:
      ignore:
        paths:
          - '../client/node_modules'
      alpha: "../client"
      beta: "volume://code-front"
      mode: "two-way-resolved"
      configurationBeta:
        permissions:
          defaultOwner: "id:1000"
          defaultGroup: "id:1000"
```

You can also change the permission mode, but the default should be sufficient.  For more information on the available settings, you can check out [this page](https://mutagen.io/documentation/synchronization/permissions).

Once you make this change, you'll need to remove the existing volume since Mutagen won't overwrite the existing file permissions for files that it's not updating (meaning they'll remain with `root` ownership).  You can do this by bringing down the Compose project with the `--volumes` flag or by manually removing the volume with `docker volume rm`.

Just to aid in future debugging:

You can check out the permissions on files by dropping into a shell in the Mutagen sidecar container:

```
$ mutagen-compose exec mutagen /bin/sh
$ ls -lash /volumes/code-front
```

Also, in this case I was able to determine the target UID/GID using [this tool](https://contains.dev/). In this case it's obvious which UID/GID are being used based on the commands, but it won't always be, so you can also look in `/etc/shadow` and `/etc/group` to grab the UID/GID if you know the user and group you're interested in (and you'll usually have to do that if it's a distro-provided user such as `www-data`).

Feel free to ping if that doesn't solve the issue!
