### ISSUE TITLE
File changes on local did not sync to the container

### ISSUE THREAD

**Issue by matrixhcl** [mutagen-io/mutagen-compose#7]
Platform: MacBook Pro (13-inch, 2020, Four Thunderbolt 3 ports)
macOS Version: 12.1

My docker compose mutagen setting is pretty straight forward:
```
# Define synchronization and forwarding sessions
x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
    code:
      alpha: "."
      beta: "volume://code"
```

Possible way to reproduce it:
1. Run `mutagen-compose up -d`
2. Try to edit something on local file, changes will be synced to the container
3. Restarted the macbook and reset NVRAM several times due to some hardware failure
4. Checked that the mutagen container is gone, so I `mutagen-compose down` and `mutagen-compose up -d` to restart it
5. Try to edit something on local file again, it seems that changes will not be synced to the container.
6. Remove the volume created by mutagen and try `mutagen-compose down` and `mutagen-compose up -d` again, sync works fine again.
