### ISSUE TITLE
Error response from daemon: network  is ambiguous

### ISSUE THREAD

**Issue by fsmeier** [mutagen-io/mutagen-compose#81]
After updating to version 0.18.0 several users reported an error. 
I think I was able to reproduce it:

### Expected behaviour:
`mutagen-compose up` runs without any problems

### Actual behaviour: 
`mutagen-compose up` returns an exception.

```shell
projects mutagen-compose up                
[+] Running 2/2
 ✔ Network test_123_private      Created                                                                                                                                                      0.1s 
 ✔ Container projects-mutagen-1  Created                                                                                                                                                      0.1s 
unable to bring up Mutagen Compose sidecar service: Error response from daemon: network  is ambiguous (4 matches found based on ID prefix)
```

### How to reproduce?
Example `docker-compose.yml`
```yml
services:
    test:
        image: "redis:alpine"
        networks:
            - private

x-mutagen:
    sync:
        defaults:
            symlink:
                mode: posix-raw
            ignore:
                paths:
                    - '.git*'
                    - '.idea'
                    - '.DS_Store'
            permissions:
                defaultFileMode: 0666
                defaultDirectoryMode: 0777

networks:
    public:
        name: test_123_public
    private:
        name: test_123_private
```

Terminal commands executed:

```shell
➜  projects git:(master) ✗ docker ps     
CONTAINER ID   IMAGE     COMMAND   CREATED   STATUS    PORTS     NAMES
➜  projects git:(master) ✗ docker network ls
NETWORK ID     NAME      DRIVER    SCOPE
51f20da645ff   bridge    bridge    local
3177b34dfa2e   host      host      local
5fd5846a48bc   none      null      local
➜  projects git:(master) ✗ mutagen-compose up                                 
[+] Stopping 2/0
 ✔ Container projects-mutagen-1  Stopped                                                                                                                                                 0.0s 
 ✔ Mutagen                            Paused                                                                                                                                                  0.0s 
[+] Running 1/1
 ✔ Network test_123_private           Created                                                                                                                                                 0.1s 
 ⠋ Container projects-mutagen-1  Starting                                                                                                                                                0.0s 
unable to bring up Mutagen Compose sidecar service: Error response from daemon: network  is ambiguous (4 matches found based on ID prefix)
➜  projects git:(master) ✗ docker network ls 
NETWORK ID     NAME               DRIVER    SCOPE
51f20da645ff   bridge             bridge    local
3177b34dfa2e   host               host      local
5fd5846a48bc   none               null      local
79a369b162cf   test_123_private   bridge    local
```

### System

**Versions:**
Mutagen(compose) version 0.18.0
Compose version v2.23.3
Docker version v24.0.7

**Platform:**
MacOS 15.0.1 with Intel CPU
