### ISSUE TITLE
mutagen-compose slower than mutagen standalone?

### ISSUE THREAD

**Issue by velser** [mutagen-io/mutagen-compose#9]
Hello.

Testing out mutagen and noticed that mutagen-compose has lower performance. Not sure whether it is like it is at the current state or am I doing something wrong.

System: MacOS 12.1
CPU: M1 Max

Example with standalone mutagen (after docker-compose up -d):
`mutagen sync create -m two-way-resolved --name=code /Users/x/projectcode docker://root@projectapi/var/www/html`

Example with compose x-mutagen:

```
version: '3.7'

services:
  api:
    container_name: projectapi
    build:
      context: ../
    volumes:
      - code:/var/www/html
    ports:
      - 8000:80

volumes:
  code:

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true

    code:
      mode: two-way-resolved
      alpha: /Users/x/projectcode
      beta: volume://code
```

With **standalone** I get response in 20-40ms, with **compose** I get 70ms+

Any help appreciated
